#!/bin/bash

############################################
# When the container is running, you can use
#   this script to enter the container and
#   see how it is configured.
############################################

docker run -t -i --rm srp33/goodnomen:v1 /bin/bash
