#Load libraries ----------------------------------------------------------
loadLibraries <- "#Load Libraries
library(DT)
library(RCurl)
library(rhandsontable)
library(rjson)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinybusy)
library(shinyjs)
library(tidyverse)
library(tools)
library(writexl)
library(readxl)
library(httr)
library(tidytext)
library(dplyr)
library(readr)
library(tidyr)
library(stringdist)
library(feather)
data(stop_words)"

eval(parse(text = loadLibraries))