#!/bin/bash

######################################################
# This script has the logic for executing
# Good Nomen within a Docker container after
# the Docker image has been created.
# It will run on port 80 (this can be changed).
# It should be accessible from a browser at
#   http://localhost:80/GoodNomen
# You must have an API key for BioPortal in
#   this directory when you execute this script.
#   This file should be called BioPortalApiKey.txt.
#######################################################

## This will execute the container in interactive mode.
## Hit Ctrl-C when you want to close the container.
docker run --rm -i -t --name goodnomen -p 80:3838 \
    -v /tmp:/tmp \
    srp33/goodnomen:v$(cat VERSION)

#docker run --rm -i -t srp33/goodnomen:v$(cat VERSION) /bin/bash
