#!/bin/bash

######################################################
# This script has the logic for executing
# Good Nomen within a Docker container after
# the Docker image has been created.
# It will run on port 8080.
# It should be accessible from a browser at
#   http://localhost:8080/GoodNomen
# You must have an API key for BioPortal in
#   this directory when you execute this script.
#   This file should be called BioPortalApiKey.txt.
#######################################################

## This will execute the container in detached mode.
## This means it will continue running after you log out.
#docker run --rm -d --name goodnomen -p 8080:3838 \
#    -v $(pwd):/keys \
#    srp33/goodnomen:v2

## This will execute the container in interactive mode.
## Hit Ctrl-C when you want to close the container.
docker run --rm -i -t --name goodnomen -p 8080:3838 \
    -v $(pwd):/keys \
    srp33/goodnomen:v1
    #-v /tmp:/tmp \
